//! Tests for src/detect/extract.rs — bounded-format text extraction.
//!
//! Mirrors dlp-management-server/test/extract.test.js (X01–X21) and runs
//! against the SAME fixtures in dlp-management-server/test/fixtures/extract/
//! (generated by gen-fixtures.js there). Byte-identical text is not the
//! contract — same readable formats, same expected substrings, and the same
//! UnreadableError reason codes are.

use dlp_agent::detect::extract::{extract_text, ExtractedText, Unreadable, MAX_BUFFER_BYTES};
use std::path::{Path, PathBuf};

fn fixtures_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../dlp-management-server/test/fixtures/extract")
}

fn fixture(name: &str) -> Vec<u8> {
    let path = fixtures_dir().join(name);
    std::fs::read(&path).unwrap_or_else(|e| {
        panic!(
            "cannot read fixture {} — run `node test/fixtures/extract/gen-fixtures.js` \
             in dlp-management-server first: {e}",
            path.display()
        )
    })
}

fn extract_fixture(name: &str) -> Result<ExtractedText, Unreadable> {
    extract_text(&fixture(name), name)
}

/// Assert the result is Unreadable with the given server reason code.
fn expect_unreadable(result: Result<ExtractedText, Unreadable>, reason: &str) -> Unreadable {
    match result {
        Ok(out) => panic!(
            "expected Unreadable('{reason}') but extraction succeeded (format {})",
            out.format
        ),
        Err(err) => {
            assert_eq!(err.reason.code(), reason, "wrong refusal reason");
            err
        }
    }
}

// ---- plain text family -------------------------------------------------

// X01
#[test]
fn plain_txt_extracts_as_utf8_format_text() {
    let out = extract_fixture("sample.txt").expect("sample.txt should extract");
    assert_eq!(out.format, "text");
    assert!(out.text.contains("OPERATION LIONHEART"), "missing expected substring");
    assert!(out.text.contains("Second line."), "missing second line");
}

// X02
#[test]
fn utf8_bom_is_stripped_and_accents_survive() {
    let out = extract_fixture("sample-bom.txt").expect("sample-bom.txt should extract");
    assert!(!out.text.starts_with('\u{feff}'), "BOM leaked into text");
    assert!(out.text.contains("café résumé naïve"), "accented text mangled");
}

// X03
#[test]
fn utf16le_bom_decodes() {
    let out = extract_fixture("sample-utf16le.txt").expect("utf16le should extract");
    assert!(out.text.contains("WIDECHAR SECRET"), "utf16le not decoded");
}

// X04
#[test]
fn utf16be_bom_decodes() {
    let out = extract_fixture("sample-utf16be.txt").expect("utf16be should extract");
    assert!(out.text.contains("BIGENDIAN SECRET"), "utf16be not decoded");
}

// X05
#[test]
fn md_and_csv_extract_as_text() {
    let md = extract_fixture("sample.md").expect("sample.md should extract");
    assert!(md.text.contains("KEYWORD_MD") && md.format == "text");
    let csv = extract_fixture("sample.csv").expect("sample.csv should extract");
    assert!(csv.text.contains("CSV_ROW_ALPHA") && csv.format == "text");
}

// X06
#[test]
fn txt_with_nul_bytes_is_binary_content() {
    expect_unreadable(extract_fixture("binary.txt"), "binary-content");
}

// X07
#[test]
fn txt_with_invalid_utf8_is_binary_content() {
    expect_unreadable(extract_fixture("badutf8.txt"), "binary-content");
}

// ---- OOXML -------------------------------------------------------------

// X08
#[test]
fn docx_extracts_body_header_footer_and_decodes_entities() {
    let out = extract_fixture("sample.docx").expect("sample.docx should extract");
    assert_eq!(out.format, "docx");
    assert!(out.text.contains("PROJECT AEGIS"), "body missing");
    assert!(out.text.contains("HEADER-MARKING-SECRET"), "header part missing");
    assert!(out.text.contains("FOOTER-PAGE-MARK"), "footer part missing");
    assert!(
        out.text.contains(r#"fish & chips <classified> "q" 'a'"#),
        "XML entities not decoded"
    );
    assert!(!out.text.contains("&amp;"), "entity left encoded");
}

// X09
#[test]
fn docx_paragraphs_are_newline_separated() {
    let out = extract_fixture("sample.docx").expect("sample.docx should extract");
    let lines: Vec<&str> = out.text.split('\n').collect();
    assert!(
        lines.iter().any(|l| l.contains("PROJECT AEGIS")),
        "para 1 not on own line"
    );
    assert!(
        lines.iter().any(|l| l.contains("fish & chips")),
        "para 2 not on own line"
    );
    assert!(
        !lines
            .iter()
            .any(|l| l.contains("PROJECT AEGIS") && l.contains("fish & chips")),
        "paragraphs ran together"
    );
}

// X10
#[test]
fn xlsx_extracts_shared_and_inline_strings() {
    let out = extract_fixture("sample.xlsx").expect("sample.xlsx should extract");
    assert_eq!(out.format, "xlsx");
    assert!(out.text.contains("SHARED-STRING-ONE"), "shared string missing");
    assert!(
        out.text.contains("Budget & forecast"),
        "entity in shared string not decoded"
    );
    assert!(out.text.contains("INLINE-CELL-TEXT"), "inline sheet string missing");
}

// X11
#[test]
fn pptx_extracts_slides_in_order_newline_separated() {
    let out = extract_fixture("sample.pptx").expect("sample.pptx should extract");
    assert_eq!(out.format, "pptx");
    let one = out.text.find("SLIDE-ONE-TITLE").expect("slide 1 text missing");
    let two = out.text.find("SLIDE-TWO-BODY").expect("slide 2 text missing");
    assert!(one < two, "slides out of order");
    assert!(
        out.text[one..two].contains('\n'),
        "slides not newline-separated"
    );
}

// ---- PDF ---------------------------------------------------------------

// X12
#[test]
fn pdf_text_layer_extracts() {
    let out = extract_fixture("sample.pdf").expect("sample.pdf should extract");
    assert_eq!(out.format, "pdf");
    assert!(out.text.contains("PDF-TEXT-LAYER-MARK"), "pdf text missing");
}

// X13
#[test]
fn scanned_pdf_without_text_layer_refuses() {
    expect_unreadable(extract_fixture("scanned.pdf"), "no-text-layer");
}

// ---- zip recursion -----------------------------------------------------

// X14
#[test]
fn zip_recurses_into_supported_members_skips_others_silently() {
    let out = extract_fixture("nested.zip").expect("nested.zip should extract");
    assert_eq!(out.format, "zip");
    assert!(out.text.contains("TOP-LEVEL-TEXT"), "top-level member missing");
    assert!(out.text.contains("DEEP-NESTED-TEXT"), "nested-zip member missing");
    assert!(out.text.contains("ZIP-MD-MEMBER"), ".md member missing");
    assert!(!out.text.contains('\u{0000}'), "binary member leaked into text");
}

// X15
#[test]
fn zip_depth_cap_level3_reachable_level4_skipped() {
    let out = extract_fixture("deep.zip").expect("deep.zip should extract");
    assert!(
        out.text.contains("LEVEL-THREE-TEXT"),
        "depth-3 text should be reachable"
    );
    assert!(
        !out.text.contains("LEVEL-FOUR-TEXT"),
        "depth-4 text should have been skipped"
    );
}

// ---- encryption / corruption / bounds ----------------------------------

// X16
#[test]
fn encrypted_zip_refuses_whole_container() {
    expect_unreadable(extract_fixture("encrypted.zip"), "encrypted-container");
}

// X17
#[test]
fn password_protected_office_file_cfb_magic_refuses() {
    expect_unreadable(extract_fixture("protected.docx"), "encrypted-container");
}

// X18
#[test]
fn non_zip_bytes_under_docx_name_is_corrupt_container() {
    expect_unreadable(extract_fixture("corrupt.docx"), "corrupt-container");
}

// X19
#[test]
fn unsupported_extension_refuses() {
    expect_unreadable(
        extract_text(b"MZ fake executable", "tool.exe"),
        "unsupported-format",
    );
    expect_unreadable(extract_text(b"no extension", "README"), "unsupported-format");
}

// X20
#[test]
fn buffer_over_100mb_is_too_large_before_format_dispatch() {
    let big = vec![0u8; MAX_BUFFER_BYTES + 1];
    expect_unreadable(extract_text(&big, "huge.txt"), "too-large");
}

// X21
#[test]
fn unreadable_shape_display_equals_reason_code() {
    let err = expect_unreadable(extract_fixture("encrypted.zip"), "encrypted-container");
    assert_eq!(err.to_string(), err.reason.code(), "Display must equal reason code");
    // std::error::Error impl exists (server: Error subclass)
    let _: &dyn std::error::Error = &err;
}
