//! Gate for `src/livebundle.rs` — a long-running channel must enforce a newly
//! downloaded fingerprint index WITHOUT a restart, and must never trade a good
//! in-memory index for a worse one.
//!
//! Before this module every channel (kguard, the USB monitor, the clipboard
//! monitor, the browser-upload host) loaded `index.dlpx` once at start-up, so:
//! a document registered today was not enforced on USB until the service
//! restarted; and a channel that started with no index stayed blind even after
//! one was downloaded — on the kguard write path that skips the ML classifier
//! too.
//!
//! Fixtures (`tests/fixtures/livebundle/`, regenerated by
//! `dlp-management-server/scripts/gen-livebundle-fixture.js`) are real bundles
//! signed by the dev CA:
//!
//! * `v1.bundle` — version 1, registers ONLY "Fixture Plan Alpha";
//! * `v2.bundle` — version 2, registers Alpha AND "Fixture Plan Bravo";
//! * `v3.bundle` — version 3, same documents as v2;
//! * `bravo.txt` — Bravo's text: it matches v2/v3 and does NOT match v1.
//!
//! So the central test does not merely watch a version number move — it shows
//! the DETECTION of a real document change from "no match" to "match" on a
//! running channel.
//!
//! Every write below goes through `Storage::store_index_bundle`, the exact
//! function the check-in worker uses, so the reload is tested against the real
//! writer rather than a hand-rolled file copy.

use std::path::{Path, PathBuf};
use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::Arc;
use std::time::{Duration, Instant};

use dlp_agent::detect::verdict_text;
use dlp_agent::livebundle::{LiveBundle, Refresh};
use dlp_agent::storage::Storage;

fn fixture(name: &str) -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/livebundle").join(name)
}

fn bytes(name: &str) -> Vec<u8> {
    std::fs::read(fixture(name)).unwrap_or_else(|e| panic!("fixture {name}: {e}"))
}

fn bravo_text() -> String {
    std::fs::read_to_string(fixture("bravo.txt")).unwrap()
}

/// A fresh, UNENROLLED state dir (no identity), so the CA is resolved from the
/// installer-provisioned `ca_cert_path` — the fixtures' signing CA.
struct Env {
    state: PathBuf,
    ca: PathBuf,
}

impl Env {
    fn new(tag: &str) -> Env {
        let root = std::env::temp_dir().join(format!(
            "dlp-livebundle-{tag}-{}-{}",
            std::process::id(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .as_nanos()
        ));
        let _ = std::fs::remove_dir_all(&root);
        let state = root.join("state");
        std::fs::create_dir_all(&state).unwrap();
        let ca = root.join("ca-cert.pem");
        std::fs::copy(fixture("ca-cert.pem"), &ca).unwrap();
        Env { state, ca }
    }
    fn storage(&self) -> Storage {
        Storage::new(self.state.clone())
    }
    /// Install a bundle the way the check-in worker does.
    fn install(&self, name: &str) {
        self.storage().store_index_bundle(&bytes(name)).unwrap();
    }
    /// Put raw bytes on disk WITHOUT the downloader's checks — what a torn
    /// write, a tamperer, or an old build could leave behind.
    fn plant(&self, raw: &[u8]) {
        std::fs::write(self.storage().index_bundle_path(), raw).unwrap();
    }
    fn open(&self) -> LiveBundle {
        LiveBundle::open(&self.state, &self.ca, "test")
    }
}

impl Drop for Env {
    fn drop(&mut self) {
        if let Some(root) = self.state.parent() {
            let _ = std::fs::remove_dir_all(root);
        }
    }
}

fn bravo_is_detected(lb: &LiveBundle) -> bool {
    let b = lb.current().expect("a bundle must be live");
    verdict_text(&bravo_text(), &b)
        .idm
        .iter()
        .any(|m| m.title == "Fixture Plan Bravo")
}

// ===========================================================================
// The two defects this module exists to fix
// ===========================================================================

/// A channel that started with NO index (a fresh install, or one whose index
/// was lost) must start enforcing as soon as one is downloaded — not at the
/// next service restart.
#[test]
fn a_channel_that_started_with_no_index_picks_one_up_without_a_restart() {
    let env = Env::new("empty-start");
    let lb = env.open();
    assert!(lb.current().is_none(), "nothing on disk yet");
    assert_eq!(lb.refresh(), Refresh::Unchanged, "still nothing — and not re-examined");

    env.install("v1.bundle");
    assert_eq!(lb.refresh(), Refresh::Loaded { from: None, to: 1 });
    assert_eq!(lb.version(), Some(1));
}

/// THE central property: a document registered AFTER the channel started is
/// enforced on the running channel once its index is downloaded.
#[test]
fn a_document_registered_after_start_is_detected_once_its_index_is_downloaded() {
    let env = Env::new("new-doc");
    env.install("v1.bundle");
    let lb = env.open();
    assert_eq!(lb.version(), Some(1));
    assert!(
        !bravo_is_detected(&lb),
        "v1 does not register Bravo — the fixture is wrong if this matches"
    );

    // The console registers Bravo; the check-in worker downloads v2.
    env.install("v2.bundle");
    assert_eq!(lb.refresh(), Refresh::Loaded { from: Some(1), to: 2 });
    assert!(
        bravo_is_detected(&lb),
        "after the reload the running channel must detect the newly registered document"
    );
}

// ===========================================================================
// Never trade a good in-memory index for a worse one
// ===========================================================================

#[test]
fn a_corrupt_file_on_disk_never_replaces_the_verified_bundle_in_memory() {
    let env = Env::new("corrupt");
    env.install("v2.bundle");
    let lb = env.open();

    // A torn/garbage file — exactly what a power cut mid-write used to leave.
    env.plant(b"this is not a bundle");
    assert_eq!(lb.refresh(), Refresh::Rejected);
    assert_eq!(lb.version(), Some(2), "the verified v2 stays live");
    assert!(bravo_is_detected(&lb), "and it still enforces");
    assert_eq!(lb.rejections(), 1);

    // The same bad bytes are not re-verified on every tick.
    assert_eq!(lb.refresh(), Refresh::Unchanged);
    assert_eq!(lb.rejections(), 1);

    // When a good bundle lands again it is picked up.
    env.install("v3.bundle");
    assert_eq!(lb.refresh(), Refresh::Loaded { from: Some(2), to: 3 });
}

#[test]
fn a_tampered_bundle_fails_the_signature_check_and_is_ignored() {
    let env = Env::new("tamper");
    env.install("v1.bundle");
    let lb = env.open();

    let mut evil = bytes("v2.bundle");
    let mid = evil.len() / 2;
    evil[mid] ^= 0xFF; // one flipped byte anywhere must fail verification
    env.plant(&evil);
    assert_eq!(lb.refresh(), Refresh::Rejected);
    assert_eq!(lb.version(), Some(1), "a tampered v2 must not go live");
}

#[test]
fn a_missing_file_keeps_the_verified_bundle_in_memory() {
    let env = Env::new("missing");
    env.install("v2.bundle");
    let lb = env.open();

    std::fs::remove_file(env.storage().index_bundle_path()).unwrap();
    assert_eq!(lb.refresh(), Refresh::Missing);
    assert_eq!(lb.version(), Some(2), "losing the FILE must not lose the index");
    assert!(bravo_is_detected(&lb));
    assert_eq!(lb.refresh(), Refresh::Unchanged, "absence is noted once");

    env.install("v3.bundle");
    assert_eq!(lb.refresh(), Refresh::Loaded { from: Some(2), to: 3 });
}

/// The same monotonic rule the downloader applies: an older bundle — even a
/// validly signed one — must not quietly un-register documents.
#[test]
fn an_older_validly_signed_bundle_is_never_rolled_back_to() {
    let env = Env::new("rollback");
    env.install("v3.bundle");
    let lb = env.open();

    env.plant(&bytes("v1.bundle"));
    assert_eq!(lb.refresh(), Refresh::KeptNewer { on_disk: 1, live: 3 });
    assert_eq!(lb.version(), Some(3));
    assert!(bravo_is_detected(&lb), "v1 would have dropped Bravo");
}

#[test]
fn a_rewrite_of_the_same_version_is_not_counted_as_a_reload() {
    let env = Env::new("same");
    env.install("v2.bundle");
    let lb = env.open();
    assert_eq!(lb.reloads(), 1, "the initial load");

    std::thread::sleep(Duration::from_millis(20)); // a distinct modification time
    env.install("v2.bundle");
    assert_eq!(lb.refresh(), Refresh::SameVersion(2));
    assert_eq!(lb.reloads(), 1);
}

#[test]
fn without_a_ca_nothing_loads_and_it_is_retried_not_remembered() {
    let env = Env::new("noca");
    env.install("v1.bundle");
    std::fs::remove_file(&env.ca).unwrap();
    let lb = env.open();
    assert!(lb.current().is_none(), "no trust anchor, no bundle");
    assert_eq!(lb.refresh(), Refresh::Transient);

    // The CA appears (installer repair): the SAME file must now load, which
    // only works if the earlier attempt was not remembered as "considered".
    std::fs::copy(fixture("ca-cert.pem"), &env.ca).unwrap();
    assert_eq!(lb.refresh(), Refresh::Loaded { from: None, to: 1 });
}

// ===========================================================================
// The watcher thread, and readers racing a reload
// ===========================================================================

/// The watcher alone — no manual `refresh` — must bring the new index live.
#[test]
fn the_watcher_thread_brings_a_new_index_live_on_its_own() {
    let env = Env::new("watcher");
    env.install("v1.bundle");
    let lb = LiveBundle::start(&env.state, &env.ca, "test-watch", Duration::from_millis(25));
    assert_eq!(lb.version(), Some(1));

    env.install("v2.bundle");
    let deadline = Instant::now() + Duration::from_secs(10);
    while lb.version() != Some(2) {
        assert!(Instant::now() < deadline, "the watcher never picked up v2");
        std::thread::sleep(Duration::from_millis(10));
    }
    assert!(bravo_is_detected(&lb));
}

/// Readers taking a snapshot per event while the index is replaced must never
/// see "no bundle" and never see the version go backwards.
#[test]
fn readers_never_see_the_index_disappear_or_go_backwards_during_reloads() {
    let env = Env::new("race");
    env.install("v1.bundle");
    let lb = LiveBundle::start(&env.state, &env.ca, "test-race", Duration::from_millis(5));

    let stop = Arc::new(AtomicBool::new(false));
    let readers: Vec<_> = (0..4)
        .map(|_| {
            let (lb, stop) = (lb.clone(), stop.clone());
            std::thread::spawn(move || {
                let mut last = 0u64;
                let mut reads = 0u64;
                while !stop.load(Ordering::Relaxed) {
                    let v = lb.version().expect("the index must never disappear under a reader");
                    assert!(v >= last, "version went backwards: {last} -> {v}");
                    last = v;
                    reads += 1;
                }
                reads
            })
        })
        .collect();

    for name in ["v2.bundle", "v3.bundle"] {
        std::thread::sleep(Duration::from_millis(40));
        env.install(name);
    }
    let deadline = Instant::now() + Duration::from_secs(10);
    while lb.version() != Some(3) {
        assert!(Instant::now() < deadline, "v3 never went live");
        std::thread::sleep(Duration::from_millis(5));
    }
    stop.store(true, Ordering::Relaxed);
    for r in readers {
        assert!(r.join().expect("a reader panicked") > 0);
    }
}
