//! Golden gate for the ML chunk geometry (src/ml/chunk.rs).
//!
//! The contract is dlp-agent/tests/fixtures/ml-golden-vectors.json, generated by
//! the torch-free Python reference in tools/ml-reference/. For every case the
//! chunk COUNT, the chunk LENGTHS and the SHA-256 of the chunk ids must be
//! identical to what the reference produced. Geometry is exact — there is no
//! tolerance here and there must never be one: a single token's difference
//! changes what the encoder sees, which changes the label, which changes whether
//! a document is blocked at a USB port. A failure here is a real divergence, not
//! a flaky test.
//!
//! This file deliberately needs ONLY `backbone/tokenizer.json` (466 KB), never
//! `model/model.onnx` (256 MB) and never the ONNX Runtime. The geometry half of
//! the suite therefore runs on every commit and on every developer box; the
//! logits half lives in tests/ml_golden.rs and gates on the graph being present.

use std::path::{Path, PathBuf};

use dlp_agent::ml::{chunk_ids_sha256, tokenizer_from_file, ChunkGeometry, Chunker, Encoder};
use serde::Deserialize;

// =====================================================================
// The fixture
// =====================================================================

#[derive(Deserialize)]
struct Fixture {
    #[serde(rename = "modelVersion")]
    model_version: String,
    #[serde(rename = "maxChars")]
    max_chars: usize,
    #[serde(rename = "padId")]
    pad_id: i64,
    chunking: FixtureChunking,
    labels: Vec<String>,
    cases: Vec<Case>,
}

#[derive(Deserialize)]
struct FixtureChunking {
    #[serde(rename = "maxTokens")]
    max_tokens: usize,
    #[serde(rename = "overlapTokens")]
    overlap_tokens: usize,
    #[serde(rename = "minTokens")]
    min_tokens: usize,
    #[serde(rename = "contentBudget")]
    content_budget: usize,
    #[serde(rename = "effectiveOverlap")]
    effective_overlap: usize,
}

#[derive(Deserialize)]
struct Case {
    name: String,
    #[serde(rename = "textRecipe")]
    text_recipe: TextRecipe,
    expected: Expected,
}

/// Several cases need thousands of tokens and one needs 200 000 characters, so
/// the fixture stores the recipe rather than the prose. `repeat` concatenates
/// with NO separator — any separator is already inside `text`.
#[derive(Deserialize)]
struct TextRecipe {
    kind: String,
    text: String,
    #[serde(default)]
    times: Option<usize>,
}

#[derive(Deserialize)]
struct Expected {
    #[serde(rename = "chunkCount")]
    chunk_count: usize,
    #[serde(rename = "chunkLens")]
    chunk_lens: Vec<usize>,
    #[serde(rename = "chunkIdsSha256")]
    chunk_ids_sha256: String,
    #[serde(rename = "tokenCount")]
    token_count: usize,
}

impl TextRecipe {
    fn build(&self) -> String {
        match self.kind.as_str() {
            "literal" => self.text.clone(),
            "repeat" => self.text.repeat(self.times.expect("repeat recipe needs `times`")),
            other => panic!("unknown textRecipe kind {other:?}"),
        }
    }
}

fn fixture_path() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/ml-golden-vectors.json")
}

fn tokenizer_path() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../Document_classification/backbone/tokenizer.json")
}

fn load_fixture() -> Fixture {
    let path = fixture_path();
    let raw = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("cannot read ML golden vectors at {}: {e}", path.display()));
    serde_json::from_str(&raw).expect("parsing ml-golden-vectors.json")
}

/// The tokenizer is a repository artifact, not something the build produces. A
/// tree without `Document_classification/` skips loudly rather than failing:
/// every OTHER test in the suite must still be runnable on such a box.
///
/// The concrete type is the `tokenizers` crate's, which this test deliberately
/// does not depend on: the chunker's whole interface to a tokenizer is
/// [`dlp_agent::ml::Encoder`], so that is all this hands back.
fn tokenizer_or_skip() -> Option<impl Encoder> {
    let path = tokenizer_path();
    if !path.is_file() {
        eprintln!(
            "SKIPPING ml_chunker: {} is not present. Restore the Document_classification/ \
             artifacts to run the chunk-geometry gate.",
            path.display()
        );
        return None;
    }
    Some(tokenizer_from_file(&path).unwrap_or_else(|e| panic!("loading {}: {e}", path.display())))
}

// =====================================================================
// 1. The fixture pins the geometry this port was written against.
// =====================================================================

#[test]
fn fixture_pins_the_v6_2_01_geometry() {
    let fx = load_fixture();
    assert_eq!(fx.model_version, "V6.2.01");
    assert_eq!(fx.max_chars, 200_000);
    assert_eq!(fx.pad_id, 0);
    assert_eq!(fx.chunking.max_tokens, 512);
    assert_eq!(fx.chunking.overlap_tokens, 64);
    assert_eq!(fx.chunking.min_tokens, 32);
    assert_eq!(fx.chunking.content_budget, 510);
    assert_eq!(fx.chunking.effective_overlap, 64);
    assert_eq!(fx.labels.len(), 29, "the label space is frozen at 29");
    assert!(fx.cases.len() >= 10, "expected the full geometry probe set");
}

/// The fixture's label list and the agent's frozen table are two copies of the
/// same thing; if they ever disagree, every prediction is mis-named.
#[test]
fn fixture_labels_match_the_agents_frozen_table() {
    let fx = load_fixture();
    let ours: Vec<&str> = dlp_agent::ml::LABELS.iter().map(|l| l.id).collect();
    assert_eq!(fx.labels, ours);
}

// =====================================================================
// 2. Chunk geometry reproduces the reference exactly, for every case.
// =====================================================================

#[test]
fn chunk_geometry_reproduced_exactly() {
    let Some(tokenizer) = tokenizer_or_skip() else { return };
    let fx = load_fixture();

    let geometry = ChunkGeometry {
        max_tokens: fx.chunking.max_tokens,
        overlap_tokens: fx.chunking.overlap_tokens,
        min_tokens: fx.chunking.min_tokens,
    };
    let chunker = Chunker::new(&tokenizer, geometry).expect("chunker");
    assert_eq!(chunker.content_budget, fx.chunking.content_budget);
    assert_eq!(chunker.overlap, fx.chunking.effective_overlap);

    for case in &fx.cases {
        let raw = case.text_recipe.build();

        // Truncation is by CHARACTERS and happens before a single token exists;
        // the max_chars_truncation case exists precisely to catch a port that
        // truncates by bytes or by tokens.
        let text: &str = match raw.char_indices().nth(fx.max_chars) {
            Some((byte, _)) => &raw[..byte],
            None => &raw,
        };

        let chunks = chunker.chunk(text).unwrap_or_else(|e| panic!("{}: {e}", case.name));

        assert_eq!(chunks.len(), case.expected.chunk_count, "{}: chunk count drifted", case.name);

        let lens: Vec<usize> = chunks.iter().map(Vec::len).collect();
        assert_eq!(lens, case.expected.chunk_lens, "{}: chunk lengths drifted", case.name);

        assert_eq!(
            chunk_ids_sha256(&chunks),
            case.expected.chunk_ids_sha256,
            "{}: chunk IDS drifted — the model would see different tokens",
            case.name
        );

        let tokens = chunker.count_tokens(text).unwrap_or_else(|e| panic!("{}: {e}", case.name));
        assert_eq!(tokens, case.expected.token_count, "{}: token count drifted", case.name);
    }
}

// =====================================================================
// 3. Invariants that hold for every case, stated once.
// =====================================================================

#[test]
fn every_chunk_fits_the_model_and_is_wrapped() {
    let Some(tokenizer) = tokenizer_or_skip() else { return };
    let fx = load_fixture();

    let geometry = ChunkGeometry {
        max_tokens: fx.chunking.max_tokens,
        overlap_tokens: fx.chunking.overlap_tokens,
        min_tokens: fx.chunking.min_tokens,
    };
    let chunker = Chunker::new(&tokenizer, geometry).expect("chunker");

    for case in &fx.cases {
        let raw = case.text_recipe.build();
        let text: &str = match raw.char_indices().nth(fx.max_chars) {
            Some((byte, _)) => &raw[..byte],
            None => &raw,
        };
        let chunks = chunker.chunk(text).unwrap_or_else(|e| panic!("{}: {e}", case.name));

        assert!(!chunks.is_empty(), "{}: a non-empty document must produce chunks", case.name);
        for (i, chunk) in chunks.iter().enumerate() {
            assert!(
                chunk.len() <= fx.chunking.max_tokens,
                "{} chunk {i}: {} tokens exceeds the {} position ceiling",
                case.name,
                chunk.len(),
                fx.chunking.max_tokens
            );
            // [CLS] … [SEP] for this WordPiece backbone. The chunker measures the
            // affixes rather than assuming them; this asserts what it measured.
            assert_eq!(chunk[0], 101, "{} chunk {i}: missing [CLS]", case.name);
            assert_eq!(*chunk.last().unwrap(), 102, "{} chunk {i}: missing [SEP]", case.name);
        }
    }
}

#[test]
fn whitespace_only_and_empty_text_produce_no_chunks() {
    let Some(tokenizer) = tokenizer_or_skip() else { return };
    let chunker = Chunker::new(&tokenizer, ChunkGeometry::default()).expect("chunker");
    assert!(chunker.chunk("").unwrap().is_empty());
    assert!(chunker.chunk("   \n\n\t  ").unwrap().is_empty());
}
