-- 005_incident_enrichment.sql — enrich detection incidents for the console log.
-- Adds the "who / what / action" metadata the reviewer needs, a stable human
-- reference, and a lightweight triage workflow. All additive + nullable/defaulted
-- so the existing agent insert path and older rows keep working unchanged.
-- Applied inside a transaction by db/migrate.js. No BEGIN/COMMIT here.

-- ============================================================
-- Enrichment columns.
--   seq            — monotonic id backing the human reference INC-000123.
--                    Backfills existing rows (acts as the ADD-COLUMN default).
--   action_taken   — what the agent actually did: 'blocked' | 'audited' |
--                    'read_only'. Lets the console distinguish a real block from
--                    an audit-only observation.
--   os_user        — best-effort interactive user on the endpoint ("who").
--                    Metadata only; never a credential.
--   detection_type — 'idm' | 'edm' | 'idm+edm' | null, derived from the verdict
--                    at ingest so the list can badge it without resolving.
-- ============================================================
alter table detection_incidents
  add column seq            bigint generated by default as identity,
  add column action_taken   text,
  add column os_user        text,
  add column detection_type text;

-- ============================================================
-- Reviewer triage workflow. status transitions are audited by the console;
-- the incident row itself carries the current state + who last changed it.
-- ============================================================
alter table detection_incidents
  add column status      text not null default 'new',
  add column status_note text,
  add column status_by   text,
  add column status_at   timestamptz;

-- Constrain status to the known set (a workflow, not free text).
alter table detection_incidents
  add constraint detection_incidents_status_chk
  check (status in ('new', 'reviewing', 'resolved', 'false_positive'));

-- Look an incident up by the reference a user quotes (from their toast/helpdesk),
-- and filter the console feed by triage status.
create index detection_incidents_seq_idx    on detection_incidents (seq);
create index detection_incidents_status_idx on detection_incidents (status, reported_at);
